# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Idan Lev-Yehudi"
description: >- # this means to ignore newlines until "baseurl:"
  Idan Lev-Yehudi's personal website
# twitter_username: username
github_username: IdanLevYehudi
minimal_mistakes_skin: mint
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Put every post under **/blog/** instead of the site root
collections:                # Jekyll creates a default “posts” collection,
  posts:                    # but declaring it here lets us tweak its URL.
    output: true
    permalink: /blog/:title/

# kramdown:
#   math_engine: mathjax
#   math_engine_opts:
#     preview: false
#   parse_block_html: true
#   hard_wrap: false

# Outputting
permalink: /:categories/:title/
timezone: Asia/Jerusalem # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

pagination:
  enabled: true        # <-- this single line already turns it on
  per_page: 5          #   optional; matches your page-front-matter
  permalink: /blog/page:num/   #   optional; keeps blog pages together
  first_page_url: /blog/     # <— key that moves page-1 to /blog/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate-v2
  # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Idan Lev-Yehudi"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "PhD student @ Technion Autonomous Systems Program (TASP)<br>Talpiot Alumnus"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-at"
      url: "mailto:idanlev at campus.technion.ac.il"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/idan-lev-yehudi/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/IdanLevYehudi"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=5yuc2i0UkD4C&hl=en"
      
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-at"
      url: "mailto:idanlev at campus.technion.ac.il"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/idan-lev-yehudi/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/IdanLevYehudi"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=5yuc2i0UkD4C&hl=en"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      
atom_feed:
  hide: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-3PSJDRC4CW"
    anonymize_ip: false  # default
